### ISSUE TITLE
2FA Supported?

### ISSUE THREAD

**Issue by ThePaulMichaels** [tradel/hassio-addons#1]
Thanks for all your work on this - however I can't seem to get it to work at all for me.. I do have 2FA turned on, and I know your add-on only requires a username/password.. Should I assume 2FA isn't supported at this time?

**Comment by tradel** [comment]
Not at this time. I’ll have to turn on 2FA and figure out how to support
it. Can you disable it for a while to try out the integration?

**Comment by ThePaulMichaels** [comment]
Yes, that does fix the issue, so it does seem to be 2fa related.

**Comment by ThePaulMichaels** [comment]
Given, I've only been able to get 1 camera loading through here at present. Is there a limit to the number of concurrent streams?

**Comment by ThePaulMichaels** [comment]
Hi @tradel  - any update on this limitation of not allowing 2fa?

**Comment by tradel** [comment]
I haven’t really had time to look into it yet.

**Comment by dyoung522** [comment]
First of all, I appreciate the effort you've made creating this add-on.

However, because Abode has access to sensitive information (my home security and internal camera feeds), I am unwilling to disable 2FA and would strongly advise nobody else should either.

Frankly, I consider lack of 2FA support a deal-breaker for use of this add-on, so hope you're able to find a solution sometime soon.

If it helps, here's the error I get in the log:

```log
Traceback (most recent call last):
  File "/app/spawn.py", line 95, in <module>
    abode = AbodeApiClient(username=config.abode_username, password=config.abode_password, locale=config.locale)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/abode.py", line 28, in __init__
    self.login()
  File "/app/abode.py", line 81, in login
    self._api_key = self._get_api_key()
                    ^^^^^^^^^^^^^^^^^^^
  File "/app/abode.py", line 47, in _get_api_key
    return login['token']
           ~~~~~^^^^^^^^^
KeyError: 'token'
```
