### ISSUE TITLE
Streams Not Loading

### ISSUE THREAD

**Issue by ThePaulMichaels** [tradel/hassio-addons#4]
Hello!
I've setup everything and followed the instructions exactly, and I can't load any streams. 
Webrtc (at port 1984) seems to have a listing of all cameras (including one I added yesterday), but the streams never load. Any issue of what I could/should check on the back-end?

**Comment by tradel** [comment]
Restart the container with debugging enabled and post the logs. Also try
from a different browser — not all support WebRTC correctly.

**Comment by ThePaulMichaels** [comment]
Is there an easy way to grab the logs? Seems like a TON of logs to post here.

**Comment by ThePaulMichaels** [comment]
2024-05-14 20:45:27,126 abode2rtc [INFO] Calling Home Assistant API: GET /addons/self/info
2024-05-14 20:45:27,130 abode2rtc [INFO] Checking Home Assistant configuration
2024-05-14 20:45:27,130 abode2rtc [INFO] Calling Home Assistant API: GET /core/api/config
2024-05-14 20:45:27,137 abode2rtc [INFO] Home Assistant has the Abode integration installed
2024-05-14 20:45:27,137 abode2rtc [INFO] Getting current state of entities
2024-05-14 20:45:27,137 abode2rtc [INFO] Calling Home Assistant API: GET /core/api/states
2024-05-14 20:45:27,171 abode2rtc [INFO] Found 10 Abode cameras in Home Assistant
2024-05-14 20:45:27,179 abode2rtc [INFO] Writing go2rtc configuration to /tmp/go2rtc.yaml
2024-05-14 20:45:27,179 abode2rtc [INFO] Searching for go2rtc binary in system path
2024-05-14 20:45:27,180 abode2rtc [INFO] Found go2rtc in /usr/local/bin/go2rtc
2024-05-14 20:45:27,180 abode2rtc [INFO] Starting go2rtc...
Traceback (most recent call last):
  File "/app/spawn.py", line 120, in <module>
    run_go2rtc(go2rtc_path, go2rtc_conf)
  File "/app/spawn.py", line 61, in run_go2rtc
    if line[0].isdigit():
       ~~~~^^^
IndexError: string index out of range
